<?php

ini_set('display_errors',1);
ini_set('display_startup_errors',1);
error_reporting(-1);

function daisey_init() 
{
	//echo "<br><br><br><br><br><br><br>This uses drupal yes!";

	//$filePath = drupal_get_path('module', 'daisey') . '/files' . $_SERVER['REQUEST_URI'];

	//echo "<br>" . $filePath;

	//echo "<br>File exists: ";
	//var_dump(file_exists($filePath));

	//echo "<br>";
	//var_dump($GLOBALS["file_exists"]);

	//$tex = explode(".", $filePath);
	//echo "<br>" . $tex[count($tex) - 1];

	if(user_is_logged_in() && !menu_get_item($_GET['q'])) 
	{
		$uriWQ =  explode("?", $_SERVER["REQUEST_URI"]);

		$filePath = drupal_get_path('module', 'daisey') . '/files' . $uriWQ[0];

		if (file_exists($filePath))
		{
			$GLOBALS["file_exists"] = true;

			$tex = explode(".", $filePath);

			if (true)//$tex[count($tex) - 1] != "html" && $tex[count($tex) - 1] != "htm")
			{
				$GLOBALS["file_exists"] = false;

				$finfo = finfo_open(FILEINFO_MIME_TYPE);
				$mime = finfo_file($finfo, $filePath);
				finfo_close($finfo);

				$size = filesize($filePath);

				if (strtolower($tex[count($tex) - 1]) == "css")
				{
					$mime = "text/css";
				}
				else if (strtolower($tex[count($tex) - 1]) == "js")
				{
					$mime = "application/javascript";
				}

				$headers = array(
					header('Content-Type:' . $mime),
					header('Content-Length:' . $size),
					header('Cache-Control: max-age=604800, public'),
					);

				if (ob_get_level()) 
				{
					ob_end_clean();
				}

				foreach ($headers as $name => $value) 
				{
					drupal_add_http_header($name, $value);
				}

				drupal_send_headers();
				
				// Transfer file in 1024 byte chunks to save memory usage.
				if ($fd = fopen($filePath, 'rb')) 
				{
					while (!feof($fd)) 
					{
						print fread($fd, 1024);
					}

					fclose($fd);
				}
				else 
				{
					drupal_not_found();
				}

				drupal_exit();
			}
		}
	}
}

function daisey_page_alter(&$page)
{
	if ($GLOBALS["file_exists"])
	{
		$GLOBALS["file_exists"] = false;

		foreach (system_region_list($GLOBALS['theme_key']) as $key => $value) 
		{
			if (
				$value != "Call Us" &&
				$value != "Socials" &&
				$value != "Logo" &&
				$value != "Page Title" &&
				$value != "Navigation"
				)
			{
				unset($page[$key]);
			}
		}

		$page['content']['#markup'] = file_get_contents(drupal_get_path('module', 'daisey') . '/files' . $_SERVER['REQUEST_URI']);
	}
}