<?php

/**
 * @file
 * Short file description here.
 *
 * Long description here.
 */

/**
 * Implements hook_menu().
 */
function daisey_menu() {

  $items['example'] = array(
    'title' => 'Example Page',
    'page callback' => 'daisey_page',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_help().
 */
function daisey_help($path, $arg) {

  switch ($path) {
    case 'admin/help#daisey':

      // Return a line-break version of the README.
      $readme = file_get_contents(drupal_get_path('module', 'daisey') . '/README.txt');
      return nl2br($readme);
  }
}

/**
 * Page example callback, referenced in hook_menu().
 *
 * Description of what the page displays.
 * Second line of the description.
 *
 * @return string
 *   The content of the page.
 */
function daisey_page() {

  return 'example';
}

/**
 * Implements hook_page_build().
 *
 * Add JavaScript and CSS code to every page.
 */
function daisey_page_build() {

  drupal_add_js(drupal_get_path('module', 'daisey') . '/js/daisey.js');
  drupal_add_css(drupal_get_path('module', 'daisey') . '/css/daisey.css');

}
